before_script:
  - echo "-----开始构建----"

# Stages 表示构建阶段，这里有两个阶段 build, deploy
stages:
  - build
  - deploy
build:
  before_script:
    - echo "开始打包"
  stage: build
  tags:
    - puge-test
  only:
    - develop-test
  script:
    - ls
    - id
    - sudo npm install node-sass --unsafe-perm --save-dev
    - npm install
    - npm run build
    - mv dist /home
    - ls
    - rm -rf /home/gitlab-runner/builds
  after_script:
    - echo "打包完成"
testprod:
  stage: deploy
  tags:
    - puge-test
  only:
    - develop-test
  script:
    - rm -rf /usr/local/puge-prod/inside-dist
    - cd /home
    - mv dist /usr/local/puge-prod/inside-dist
    - rm -rf /home/dist
    - rm -rf /home/gitlab-runner/builds
  after_script:
    - echo "部署完成"


# 线上
prod-build:
  stage: build
  before_script:
    - echo "开始下载依赖，并打包..."
  tags:
    - puge-fe-prod
  # 定义了只有在被merge到了puge-prod分支上 才会执行部署脚本。
  only:
    - puge-prod
  script:
    - node -v && npm -v
    - pwd
    - echo "切换npm源并查看此源"
    - npm config set registry https://registry.npm.taobao.org/
    - npm config get registry
    - echo "开始下载node_module..."
    - npm install
    - echo "下载完成，开始打包.."
    - npm run build
    - ls
    - mv dist /home
  after_script:
    - rm -rf /home/gitlab-runner/builds
    - echo "打包完成"

prod-deploy:
  stage: deploy
  before_script:
    - echo "开始部署..."
  tags:
    - puge-fe-prod
  # 定义了只有在被merge到了puge-prode分支上 才会执行部署脚本。
  only:
    - puge-prod
  script:
    - rm -rf /usr/local/puge-prod/inside-dist/*
    - mv /home/dist/* /usr/local/puge-prod/inside-dist/
    - rm -rf /home/dist
    - echo "重新加载nginx"
    - /usr/local/webserver/nginx/sbin/nginx -s reload
  after_script:
    - rm -rf /home/gitlab-runner/builds
    - echo "部署完成"

after_script:
  - echo "----结束上线流程----"
